name: rise-environment
channels:
  - conda-forge
  # for adding the fish shell
  - mdraw
dependencies:
  ### default packages
  #- python=3.7
  #- nodejs=16
  #- pip
  #- ipywidgets==8.0.2
  #- jupyter-offlinenotebook==0.2.2
  #- jupyter-resource-usage==0.6.3
  #- jupyterlab==3.4.8
  #- jupyterhub-singleuser==1.5.0
  #- notebook==6.4.12
  #- nteract_on_jupyter==2.1.3
  
  ### custom packages
  - pandas
  # for pulling content from a content repo
  - nbgitpuller
  # for presenting Notebook as real.js slides
  - rise
  # for configuring Rise
  - traitlets
  # for tracking and visualizing code execution
  # - snoop
  # for converting Jupyter Notebooks to plain texts
  - jupytext
  # for exploring and previewing files with vim-like bindings
  - ranger-fm
  # for the friendly interactive shell, i.e., fish
  - fish-shell
  # for managing pip environments
  - pipenv
