#!/bin/bash

set -ex
# download neovim appimage
curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage --appimage-extract
# configure neovim with AstroNvim settings 
git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
# run the following to install neovim plugins after the image is built
# ./squashfs-root/AppRun +PackerSync
